---
name: test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version:
          - { py: '3.5', tox: 'py35' }
          - { py: '3.x', tox: 'py3' }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version.py }}
      - name: Install Tox
        run: pip install tox
      - name: Test
        run: tox -e ${{ matrix.version.tox }} -- -v
